# Generated by Django 5.1.7 on 2025-03-31 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_tag_product_average_rating_product_battery_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
    ]
