# Generated by Django 5.1.7 on 2025-03-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_average_rating_remove_product_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
